---
name: lint_and_format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: yamlfmt
        uses: yk-lab/yamlfmt-action@v1.0.0

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup lua
        run: |
          sudo apt-get update
          sudo apt-get install luarocks
          sudo luarocks install luacheck

      - name: Lint lua
        run: luacheck lua/

      - name: Lint yaml
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.github_token }}
          fail_on_error: true
